pipeline {
    agent { label 'node1'}
    stages {
          stage( 'clone code') {
          steps {
          
          
          
          }
             
          
          }
        
    
    }
    
       }
